### ISSUE TITLE
Both tegra dc outputs are required?

### ISSUE THREAD

**Issue by Decatf** [grate-driver/xf86-video-opentegra#52]
I'm running the current master branch (feac05833e96ff9951603eb580fc134c0dae2bb8). The device is the Ouya running Alpine Linux and xfce4.

When the second tegra dc node is disabled in device tree, there is a crash in the opentegra driver. It is easy to reproduce by rapidly changing the xfce4 theme or a system font size/dpi.

The crash does not happen when both tegra dc devices are enabled. I guess it is makes no difference to have them both enabled. I thought it was safe to disable the second dc because there is no way to use a secondary display on this device anyways.

backtrace from the crash:
```
#0  drmmode_crtc_map_rotate_bo (scrn=scrn@entry=0x65d840, crtc_num=crtc_num@entry=1) at drmmode_display.c:1471
#1  0xb6649c5c in TegraEXAModifyPixmapHeader (pPixmap=0xa00eb0, width=6, height=8, depth=8, bitsPerPixel=8, devKind=-1, pPixData=0xa43ca4) at exa.c:424
#2  0xb6af7f8c in exaModifyPixmapHeader_driver (pPixmap=0xa00eb0, width=6, height=8, depth=8, bitsPerPixel=8, devKind=-1, pPixData=0xa43ca4) at exa_driver.c:162
#3  0x00534dae in GetScratchPixmapHeader (pScreen=pScreen@entry=0x661360, width=width@entry=6, height=height@entry=8, depth=depth@entry=8,
    bitsPerPixel=bitsPerPixel@entry=8, devKind=devKind@entry=-1, pPixData=pPixData@entry=0xa43ca4) at pixmap.c:65
#4  0x0059c7d0 in ProcRenderAddGlyphs (client=<optimized out>) at render.c:1102
#5  0x00523872 in Dispatch () at dispatch.c:478
#6  0x00525f44 in dix_main (argc=10, argv=0xbecdfe44, envp=<optimized out>) at main.c:276
#7  0xb6f71e4e in libc_start_main_stage2 (main=0x5186f5 <main>, argc=10, argv=0xbecdfe44) at src/env/__libc_start_main.c:94
#8  0x0051873c in _start_c (p=<optimized out>) at crt/crt1.c:18
#9  0x00518710 in _start () at render.c:2060

```

**Comment by digetx** [comment]
@Decatf, thank you very much for the report! I tried to reproduce the problem and couldn't even start xfce4 because of the bug, will add a fixup commit to https://github.com/grate-driver/xf86-video-opentegra/pull/51 later today.

**Comment by digetx** [comment]
Should be fixed by https://github.com/grate-driver/xf86-video-opentegra/pull/51/commits/66fb69ca92d03f68496648c2aa2a2eafa6074878

**Comment by digetx** [comment]
@Decatf Awesome, thanks! The fix will get into the master soon'ish with the rest of the changes. I'm closing this issue now since it is resolved. Thanks again and please let us know if you'll spot anything else.
